// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-pNSGbTUUbOMsReU46spQ4yv1NQkWsM',
    appId: '1:118117704286:web:5d6e1d00dba19234a94acf',
    messagingSenderId: '118117704286',
    projectId: 'landify-18ff9',
    authDomain: 'landify-18ff9.firebaseapp.com',
    storageBucket: 'landify-18ff9.firebasestorage.app',
    measurementId: 'G-SK38LQN4G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApN-ZgcaTiVyvRDg7BvyQTeafOGHQXzho',
    appId: '1:118117704286:android:1fad111b5b1fe15da94acf',
    messagingSenderId: '118117704286',
    projectId: 'landify-18ff9',
    storageBucket: 'landify-18ff9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCekD18bkG0vwM6rrnRe1s_2Q45P6Ip8WQ',
    appId: '1:118117704286:ios:3779ec8aeca75341a94acf',
    messagingSenderId: '118117704286',
    projectId: 'landify-18ff9',
    storageBucket: 'landify-18ff9.firebasestorage.app',
    androidClientId: '118117704286-djb1rt5io6gtues7lfsnfrh5gvhld030.apps.googleusercontent.com',
    iosClientId: '118117704286-ussmkei8ms18unf02cv0qvgos2bnqu3e.apps.googleusercontent.com',
    iosBundleId: 'com.khoa.landify.landifymobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH-pNSGbTUUbOMsReU46spQ4yv1NQkWsM',
    appId: '1:118117704286:web:f7263e9bca0efa71a94acf',
    messagingSenderId: '118117704286',
    projectId: 'landify-18ff9',
    authDomain: 'landify-18ff9.firebaseapp.com',
    storageBucket: 'landify-18ff9.firebasestorage.app',
    measurementId: 'G-HDW1RGQNGX',
  );

}